name: build-and-deploy

on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@master
        with:
          node-version: 18.3.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: install yarn
        run: npm i -g yarn
      - name: install dependencies
        run: yarn install
      - name: test
        run: yarn test

  publish:
    runs-on: macos-latest
    needs: test

    steps:
      - uses: actions/setup-node@master
        with:
          node-version: 18.3.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: install yarn
        run: npm i -g yarn
      - name: install dependencies
        run: yarn install

      - name: build
        run: yarn build

      - name: publish
        run: npx semantic-release
